version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: appraise
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: appraise
      POSTGRES_DB: appraise_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: